require_relative 'root'
require_relative 'tracks'
require_relative 'albums'
require_relative 'artists'
require_relative 'streams'
require_relative 'search'
require_relative 'upload'
require_relative 'playlists'
