require 'securerandom'

require 'routes/root'
require 'routes/tracks'
require 'routes/albums'
require 'routes/artists'
require 'routes/streams'
require 'routes/search'
require 'routes/upload'
require 'routes/playlists'
require 'routes/logs'
require 'routes/radio'
require 'routes/info'
require 'routes/tags'
